version: '3.9'

services:
  php:
    build: .
    container_name: php-apache
    links:
      - maildev:maildev
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - 1080:80